/*
 * This source file was generated by the Gradle 'init' task
 */
package talk;

import picocli.CommandLine;
import talk.core.TalkRunner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new TalkRunner()).execute(args);
        System.exit(exitCode);
    }
}
